#!/usr/bin/env node
/**
 * draft-article.js
 *
 * Stage 2 of the content-agent pipeline: reads news-items.json (written by
 * fetch-news.js earlier in the same CI job), asks the Claude API to draft
 * one roundup article synthesizing the relevant items, and writes a
 * publish-ready HTML page to news/. Writes nothing if there's nothing
 * relevant to draft, or if the draft fails the guardrail check.
 *
 * Usage:
 *   node draft-article.js              (calls the real Claude API — needs ANTHROPIC_API_KEY)
 *   node draft-article.js --dry-run    (skips the API call, writes a fixed placeholder draft)
 *
 * Requires: npm install @anthropic-ai/sdk
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Anthropic from '@anthropic-ai/sdk';
import { checkGuardrails } from './guardrails.js';
import { articleFilePath, renderArticle } from './article-template.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const NEWS_ITEMS_PATH = path.join(__dirname, 'data', 'news-items.json');
const REPO_ROOT = path.join(__dirname, '..', '..');

const SYSTEM_PROMPT = `You are the editorial voice of BorrowClever, an independent Irish personal loan and credit card comparison site. Write a short roundup article (300-500 words) synthesizing the news items you're given into one coherent piece — not a bulleted list of unrelated blurbs.

Rules you must follow:
- Never state a specific interest rate, APR, or fee figure (e.g. "7.2%"), even if a source item mentions one. Refer to rate moves qualitatively instead (e.g. "the ECB is expected to raise rates").
- Never assess a named lender's financial stability, safety, or creditworthiness. Report what the source said; don't editorialize about the institution.
- End the body with a short paragraph making clear this is not financial advice, in the spirit of: "This is general commentary, not financial advice. Always confirm current rates and terms directly with a lender before applying."
- Link out to original source articles where natural, using the "link" field from the provided items.
- Body must be a semantic HTML fragment using only these tags: h2, h3, p, ul, li, a, strong, em. No head/nav/full-page markup, no inline styles, no html/body tags.

Call the submit_draft tool with your finished draft. Do not respond with plain text.`;

const DRAFT_TOOL = {
  name: 'submit_draft',
  description: 'Submit the finished article draft.',
  input_schema: {
    type: 'object',
    required: ['title', 'slug', 'metaDescription', 'bodyHtml'],
    properties: {
      title: { type: 'string', description: 'Article headline, no site name suffix.' },
      slug: { type: 'string', description: 'kebab-case, no date prefix, e.g. ecb-rate-watch-and-ptsb-takeover' },
      metaDescription: { type: 'string', description: '150-160 characters, for meta description and og:description.' },
      bodyHtml: { type: 'string', description: 'Semantic HTML fragment: h2/h3, p, ul/li, a, strong/em only. No head/nav/full-page markup.' },
    },
  },
};

function isDryRun() {
  return process.argv.includes('--dry-run');
}

function readNewsItems() {
  if (!fs.existsSync(NEWS_ITEMS_PATH)) return [];
  const data = JSON.parse(fs.readFileSync(NEWS_ITEMS_PATH, 'utf8'));
  return data.items || [];
}

function dryRunDraft() {
  return {
    title: 'Dry Run: Sample Article Title',
    slug: 'dry-run-sample-article',
    metaDescription: 'Placeholder meta description from --dry-run, for testing template and file-writing plumbing without calling the Claude API.',
    bodyHtml: '<h2>Dry run</h2>\n<p>This is placeholder body content generated by --dry-run mode. No API call was made.</p>\n<p>This is general commentary, not financial advice. Always confirm current rates and terms directly with a lender before applying.</p>',
  };
}

async function draftFromClaude(items) {
  const anthropic = new Anthropic(); // reads ANTHROPIC_API_KEY from env
  const message = await anthropic.messages.create({
    model: 'claude-sonnet-5',
    max_tokens: 2048,
    system: SYSTEM_PROMPT,
    tools: [DRAFT_TOOL],
    tool_choice: { type: 'tool', name: 'submit_draft' },
    messages: [{ role: 'user', content: JSON.stringify(items, null, 2) }],
  });

  const toolUse = message.content.find((block) => block.type === 'tool_use');
  if (!toolUse) {
    throw new Error('Claude response did not include a submit_draft tool call.');
  }
  return toolUse.input;
}

async function main() {
  const items = readNewsItems();
  if (items.length === 0) {
    console.log('No relevant news items — nothing to draft.');
    return;
  }

  const draft = isDryRun() ? dryRunDraft() : await draftFromClaude(items);

  for (const field of ['title', 'slug', 'metaDescription', 'bodyHtml']) {
    if (!draft[field] || typeof draft[field] !== 'string') {
      throw new Error(`Draft is missing required field: ${field}`);
    }
  }

  const SLUG_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
  if (!SLUG_PATTERN.test(draft.slug)) {
    throw new Error(`Draft slug is not valid kebab-case: "${draft.slug}"`);
  }

  const guardrailResult = checkGuardrails(draft.bodyHtml);
  if (!guardrailResult.ok) {
    console.error(`Draft rejected: ${guardrailResult.reason}`);
    process.exit(1);
  }

  const dateIso = new Date().toISOString().slice(0, 10);
  const relativePath = articleFilePath(dateIso, draft.slug);
  const outputPath = path.join(REPO_ROOT, relativePath);
  const html = renderArticle({ ...draft, dateIso });

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, html);

  console.log(`Draft written to ${relativePath}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Fatal error in draft-article.js:', err);
    process.exit(1);
  });
