#!/usr/bin/env node
'use strict';

// Regenerates sitemap.xml from the static page list plus every file in
// guides/, examples/ and news/. Runs standalone (content-agent workflow) and
// from build.cjs, without touching any other page.

const fs   = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const BASE = 'https://borrowclever.ie';

function today() {
  return new Date().toISOString().split('T')[0];
}

function readMeta(file) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, 'data', file), 'utf8')).meta;
}

const loansMeta = readMeta('loans.json');
const cardsMeta = readMeta('cards.json');
const savingsMeta = readMeta('savings.json');

function buildSitemap() {
  const buildDate = today();
  const pages = [
    { loc: '/',             lastmod: buildDate,                    changefreq: 'weekly',  priority: '1.0' },
    { loc: '/loans.html',   lastmod: loansMeta.last_full_review,   changefreq: 'weekly',  priority: '0.9' },
    { loc: '/cards.html',   lastmod: cardsMeta.last_full_review,   changefreq: 'weekly',  priority: '0.9' },
    { loc: '/savings.html', lastmod: savingsMeta.last_full_review, changefreq: 'weekly',  priority: '0.9' },
    { loc: '/rate-tracker/', lastmod: buildDate,                   changefreq: 'weekly',  priority: '0.8' },
    { loc: '/calculator/',   lastmod: buildDate,                   changefreq: 'monthly', priority: '0.8' },
    { loc: '/about.html',   lastmod: buildDate,                    changefreq: 'monthly', priority: '0.4' },
    { loc: '/how-we-make-money.html', lastmod: buildDate,          changefreq: 'monthly', priority: '0.4' },
    { loc: '/api-docs.html', lastmod: buildDate,                   changefreq: 'monthly', priority: '0.4' },
    { loc: '/privacy.html', lastmod: buildDate,                    changefreq: 'monthly', priority: '0.2' },
  ];

  // Auto-pick up any guide pages, so new guides don't need a manual sitemap edit.
  const guidesDir = path.join(ROOT, 'guides');
  if (fs.existsSync(guidesDir)) {
    for (const file of fs.readdirSync(guidesDir).sort()) {
      if (!file.endsWith('.html')) continue;
      pages.push({ loc: `/guides/${file}`, lastmod: buildDate, changefreq: 'monthly', priority: '0.7' });
    }
  }

  // Same for the worked-example pages generated by scripts/build-worked-examples.mjs.
  const examplesDir = path.join(ROOT, 'examples');
  if (fs.existsSync(examplesDir)) {
    for (const file of fs.readdirSync(examplesDir).sort()) {
      if (!file.endsWith('.html')) continue;
      pages.push({ loc: `/examples/${file}`, lastmod: buildDate, changefreq: 'monthly', priority: '0.7' });
    }
  }

  // Same for news/ articles written by scripts/content-agent/draft-article.js.
  const newsDir = path.join(ROOT, 'news');
  if (fs.existsSync(newsDir)) {
    for (const file of fs.readdirSync(newsDir).sort()) {
      if (!file.endsWith('.html')) continue;
      pages.push({ loc: `/news/${file}`, lastmod: buildDate, changefreq: 'monthly', priority: '0.6' });
    }
  }

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    pages.map(p =>
      `  <url>\n` +
      `    <loc>${BASE}${p.loc}</loc>\n` +
      `    <lastmod>${p.lastmod}</lastmod>\n` +
      `    <changefreq>${p.changefreq}</changefreq>\n` +
      `    <priority>${p.priority}</priority>\n` +
      `  </url>`
    ).join('\n') +
    `\n</urlset>\n`;

  fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml, 'utf8');
  console.log(`[build] sitemap.xml: ${pages.length} pages | loans ${loansMeta.last_full_review} | cards ${cardsMeta.last_full_review}`);
}

buildSitemap();
